sales_force_user_name: "username"
sales_force_passwd_and_sec_token: "" # your salesforce password and security token
sales_force_site: "?.salesforce.com" # replace ? with your instancename
data_directory: "directory data show go"
email_address_from: "username"
email_address_to: "username"
smtp_host: "localhost"
